V1
Jeskay/musthave-tpl pull request #1
Opened 2024-12-25 17:39 UTC by Jeskay

1. Implemented JWT cookie authentication
2. Password hashing
3. Transactions used for operations with user balance
4. Service shutdown by syscall added

2024-12-28 14:48 UTC, bulbetski requested changes
Написал и разделил всё норм. В основнов замечания по код стайлу. Так же обрати внимание на миграции

2024-12-28 14:48 UTC, bulbetski commented on cmd/gophermart/main.go
> +	zapL := zap.Must(zap.NewProduction())
Можно брать из энвы. Параметр будет выставляться в зависимости от окружения, на котором приложуха запущена. (Рекомендация)

2024-12-28 14:48 UTC, bulbetski commented on cmd/gophermart/main.go
> +func main() {
main немного перегружен. Предлагаю сделать хелперы для создания сервера и обработки его шатдауна. createServer и handleShutdown какой-нибудь

2024-12-28 14:48 UTC, bulbetski commented on cmd/gophermart/main.go
> +	zapL := zap.Must(zap.NewProduction())
Лучше использовать zap.NewProduction as is и обработать ошибку, Must возвращает панику, а паники это не круто

2024-12-28 14:48 UTC, bulbetski commented on cmd/gophermart/main.go
> +	zapL := zap.Must(zap.NewProduction())
Еще нужно добавить defer zapL.Sync()

2024-12-28 14:48 UTC, bulbetski commented on config/config.go
> +		token2 = []byte("defaultHash")
с дефолтными значениями не очень понятно, зачем они нужны? Мб лучше просто ошибку возвращать

2024-12-28 14:48 UTC, bulbetski commented on config/config.go
> +func NewGophermartConfig() *GophermartConfig {
Вкусовщина слегка, а почему не просто Config? У тебя же в целом 1 приложение и 1 конфиг

2024-12-28 14:48 UTC, bulbetski commented on internal/auth/jwt.go
> +		ExpiresAt: time.Hour * 48,
Можно брать из энвы/из конфига

2024-12-28 14:48 UTC, bulbetski commented on internal/gophermart/db/postgrers.go
> +func (ps *PostgresStorage) init() error {
Стоит прикрутить миграции -- если долго не будет получаться, забей и оставь так. 
https://github.com/pressly/goose

2024-12-28 14:48 UTC, bulbetski commented on internal/gophermart/db/postgrers.go
> +	}
Проверка существования логина через отдельный запрос увеличивает количество запросов к базе. Вместо этого можно использовать SQL-запрос с условием на уникальность, например
```
INSERT INTO users (login, password)
VALUES ($1, $2)
ON CONFLICT (login) DO NOTHING;
```
Возвращаемое количество затронутых строк (AffectedRows) покажет, был ли добавлен пользователь.

2024-12-28 14:48 UTC, bulbetski commented on internal/gophermart/db/postgrers.go
> +func (ps *PostgresStorage) UserByLogin(login string) (*internal.User, error) {
Хорошая практика для именования функций -- действия + сущность + идентификтор, по которому получаем => GetUserByLogin

2024-12-28 14:48 UTC, bulbetski commented on internal/gophermart/db/postgrers.go
> +	if err := row.Scan(&userLogin, &userPassword, &userBalance, &userWithdrawn); err != nil {
сканировать можно сразу в поля структуры user, не нужно заводить для этого отдельные переменные

2024-12-28 14:48 UTC, bulbetski commented on internal/gophermart/db/postgrers.go
> +func (ps *PostgresStorage) AddUser(user internal.User) error {
твои DBO как будто находятся внутри пакета internal. Их нужно перенести в db/types/
или db/dbo или internal/models

2024-12-28 14:48 UTC, bulbetski commented on internal/gophermart/db/postgrers.go
> +package db
в названии файла опечатка

2024-12-28 14:48 UTC, bulbetski commented on internal/gophermart/db/postgrers.go
> +package db
так же можно разделить на 4 файла, postgres.go или repository.go, user.go, order.go, withdrawal.go

2024-12-28 14:48 UTC, bulbetski commented on internal/gophermart/db/postgrers.go
> +func (ps *PostgresStorage) OrdersByUser(login string) ([]internal.Order, error) {
GetOrdersByUserLogin или GetOrdersByUser

2024-12-28 14:48 UTC, bulbetski commented on internal/gophermart/db/postgrers.go
> +	tx, err := ps.db.BeginTx(ctx, nil)
Использование транзакций можно унифицировать, создав, например, подобный метод
```
func (ps *PostgresStorage) withTransaction(ctx context.Context, fn func(*sql.Tx) error) error {
	tx, err := ps.db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	if err := fn(tx); err != nil {
		tx.Rollback()
		return err
	}
	return tx.Commit()
}

```

2024-12-28 14:48 UTC, bulbetski commented on internal/gophermart/db/postgrers.go
> +func (ps *PostgresStorage) AddOrder(order internal.Order) error {
В методе можно поменять порядок действий, чтобы минимизировать запросы к бд. Сначала делаем insert с on conflict do nothing, и если rowsaffected == 0, то только тогда делаем select

2024-12-28 14:48 UTC, bulbetski commented on internal/gophermart/db/postgrers.go
> +			uploaded_at timestamptz
Даты можно сделать либо default current_timestamp, либо default now()
Так же для дат стоит использовать WITH TIMEZONE, потому что если будет происходить какая-то конвертация времени с учетом таймзоны в коде, то время будет втупую прибавляться или отниматься от таймстеймпа, в котором таймзоны нет

2024-12-28 14:48 UTC, bulbetski commented on internal/gophermart/db/postgrers.go
> +	_, err = ps.db.ExecContext(ctx, query, order.Number, order.User.Login, order.Status, order.Accrual, time.Now())
Если сделаешь в бд дефолтное значение для времени, не придется вставлять time.Now()

2024-12-28 14:48 UTC, bulbetski commented on internal/gophermart/db/postgrers.go
> +	return row.Err()
Возврат row.Err() не отражает результат выполнения UPDATE. Используй Exec с проверкой затронутых строк

2024-12-28 14:48 UTC, bulbetski commented on internal/gophermart/dto/order.go
> +func NewOrders(orders []internal.Order) []Order {
из internal надо перенести в dbo и сделать методы конвертации

ToDtoOrders
ToDboOrders

ну или че-то в этом духе

2024-12-28 14:48 UTC, bulbetski commented on internal/gophermart/dto/withdrawal.go
> +func NewWithdrawals(transactions []internal.Transaction) []Withdrawal {
аналогичный коммент, как и с orders

2024-12-28 14:48 UTC, bulbetski commented on internal/gophermart/errors.go
> +package gophermart
ну можно было просто сделать ошибки как переменные через errors.New, в структурах нет надобности, если они ничего в себе не содержат

2024-12-28 14:48 UTC, bulbetski commented on internal/gophermart/service.go
> +	loyaltyService *loyalty.LoyaltyService
надо заменить на интерфейсы, интерфейсы заведено определять по месту использования

2024-12-28 14:48 UTC, bulbetski commented on internal/loyalty/dto/order.go
> +func (status OrderStatus) ToInternal() internal.OrderStatus {
Тут названо правильно, только из internal куда-то надо перенести и соответствубще переименовать

2024-12-28 14:48 UTC, bulbetski commented on internal/storage.go
> +type Storage interface {
Нет особого смысла иметь общий интерфейс -- теряется смысл их использования. Помимо какого-нибудь мокирования смысл в том, чтобы ограничить конракт и использовать только те методы, которые нужны тому или иному сервису. Поэтому в местах, где ты storage свой хочешь использовать, напиши над конструктором интерфейс и в нем методы, которые сервис будет использовать -- и не больше

2024-12-28 14:48 UTC, bulbetski commented on internal/gophermart/handlers/balance.go
> +func Balance(svc *gophermart.GophermartService) gin.HandlerFunc {
У тебя должна быть структура твоего приложения, внутри которой будет твой роутер и твой сервис. Наприме type App struct {}. Ты сделаешь хэндлеры методами этого app'a. Чтобы не возвращать handlerfunc нужно, чтобы единственным аргументом твоей функции был *gin.Context

2024-12-28 14:48 UTC, bulbetski commented on internal/gophermart/handlers/balance.go
> +func Balance(svc *gophermart.GophermartService) gin.HandlerFunc {
Тогда метод balance (и все остальные) будут выглядеть пример так:
```
type app struct {
    svc *gophermart.GophermartService
}

func (a *app) Balance(c *gin.Context) {
     //     code
}

gBalance.GET("", a.Balance)
```

2024-12-28 14:48 UTC, bulbetski commented on internal/gophermart/handlers/balance.go
> +		login := ctx.GetString("Login")
На все входные параметры во всех методах нужно добавить базовую валидацию, чтобы в случае, например, отсутствия login возвращать BadRequest ошибку и дальше не проваливаться в код

2024-12-29 01:08 UTC, Jeskay commented on config/config.go
> +		token2 = []byte("defaultHash")
Чтобы не отлететь на автотестах. Ведь моих конфигов там нет, поэтому нужны какие-то значения в качестве дефлотных. Хотя можно их во флагах прописать

2025-01-11 12:22 UTC, bulbetski approved these changes
Всё ок. Только опять же, интерфейс репозитория не общий должен быть, а для каждого сервиса свой. то есть только те методы, которые нужны твоего сервиса

2025-03-26 12:21 UTC, closed without merging